function A_int_sym = integralA(y1,y2,y3,y4)
%integralA
%    A_int_sym = integralA(Y1,Y2,Y3,Y4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    18-May-2025 12:19:46

t2 = (((3.0./1.0e+1)./y2 <= 0.0) & (-1.0 <= (3.0./1.0e+1)./y2));
t3 = integral(@(lambda)lambda.*(1.0./(lambda.*y2.*1.0e+2+3.0e+1)-1.0),0.0,1.0);
t4 = log(3.0);
t6 = y1.*2.0;
t7 = y4+1.0;
t8 = -y4;
t9 = y2.*1.0e+1;
t10 = y2.*1.1e+1;
t11 = 1.0./y2.^2;
t12 = 1.0./y4;
t17 = y2./2.0;
t18 = y3./2.0;
t19 = y1./5.0;
t20 = y1.*pi.*3.0i;
t29 = 5.772156649015329e-1.*(3.3e+1./1.0e+2);
t32 = y1.*(9.0./1.0e+3);
t36 = y2.*4.95e-2;
t13 = t12.^2;
t14 = ei(t8);
t15 = exp(t8);
t16 = log(t8);
t21 = t9+3.0;
t22 = -t17;
t23 = -t18;
t24 = -t20;
t25 = -t12;
t30 = t12.*t19;
t34 = t12.*y1.*(-1.0./5.0);
t37 = -t36;
t26 = log(t21);
t27 = t15-1.0;
t28 = log(t25);
t38 = t14.*(3.3e+1./1.0e+2);
t39 = t16.*(3.3e+1./2.0e+2);
t40 = t7.*t13.*t15;
t42 = t15.*t30;
t52 = t32+t37;
t33 = t26.*y1.*3.0;
t41 = -t38;
t43 = t28.*(3.3e+1./2.0e+2);
t44 = -t40;
t46 = (t12.*t27)./5.0;
t49 = (t12.*t27)./1.0e+1;
t45 = -t43;
t48 = -t46;
t51 = t13+t44;
t53 = t19+t29+t34+t39+t41+t42+t45;
if ~all(cellfun(@isscalar,{t2}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t48+t3.*y2-(t12.*y3)./5.0-(t13.*t27.*y3)./5.0-2.0./5.0;
elseif (~t2)
    t0 = t48-(t12.*y3)./5.0+y2.*(t11.*(t4.*(3.0./1.0e+3)-t26.*(3.0./1.0e+3)+y2./1.0e+2)-1.0./2.0)-(t13.*t27.*y3)./5.0-2.0./5.0;
else
    t0 = NaN;
end
mt1 = [t0,y2.*(-1.0./4.0),0.0,0.0];
if ~all(cellfun(@isscalar,{t10,t2,t6}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (~t2)
    t0 = y1.*(-1.0./2.0)-(t11.*t52)./3.0+(t11.*t52)./t21-t4.*t11.*y1.*(3.0./1.0e+3)+t11.*t26.*y1.*(3.0./1.0e+3)-3.3e+1./2.0e+1;
elseif (t2 & (t6 == t10))
    t0 = (-Inf+t26.*3.3e+1-pi.*3.3e+1i)./(y2.*2.0e+3);
elseif (t2 & (t6 < t10))
    t0 = (t11.*(-Inf+t24+t33))./1.0e+3;
elseif (t2 & (t10 < t6))
    t0 = (t11.*(Inf+t24+t33))./1.0e+3;
else
    t0 = NaN;
end
mt2 = [t0,t23-y1./4.0-y2.*(3.0./2.0)-t12.*t27.*(3.0./1.0e+1)-5.0./8.0,t23-1.0,0.0,t25.*t53,t22,t22-t49-y3-1.0,0.0];
mt3 = [t12.*t27.*(3.3e+1./1.0e+2)-(t51.*y1)./5.0+t13.*t27.*y3.*(3.3e+1./1.0e+2)+t13.*t53.*y3+t34.*t51.*y3,t51.*y2.*(-3.0./1.0e+1),t49-(t51.*y3)./1.0e+1,-1.0];
A_int_sym = reshape([mt1,mt2,mt3],4,4);
end
